kit:
  name: "Agile Software Factory"
  link: https://github.com/griddynamics/asf
  applications:
    - name: "Agile Software Factory"
      manifest: http://gd-asf.s3.amazonaws.com/main.yaml
    - name: "ASF Webapp Demo"
      manifest: http://gd-asf.s3.amazonaws.com/asf-webapp-demo-docker-ci.yaml
    - name: "Nexus"
      manifest: http://gd-asf.s3.amazonaws.com/nexus.yaml
    - name: "Jenkins"
      manifest: http://gd-asf.s3.amazonaws.com/jenkins.yaml
    - name: "Gerrit"
      manifest: http://gd-asf.s3.amazonaws.com/gerrit.yaml
    - name: "Sonar"
      manifest: http://gd-asf.s3.amazonaws.com/sonar.yaml
    - name: "JIRA"
      manifest: http://gd-asf.s3.amazonaws.com/jira.yaml
    - name: "OpenLDAP"
      manifest: http://gd-asf.s3.amazonaws.com/ldap.yaml
    - name: "SeleniumGrid"
      manifest: https://raw.github.com/qubell-bazaar/component-selenium-grid/master/component-selenium-grid.yml
    - name: "Docker Registry"
      manifest: http://gd-asf.s3.amazonaws.com/docker-registry.yaml
    - name: "DockerVM"
      manifest: http://gd-asf.s3.amazonaws.com/docker-vm.yaml
  provider:
    name: "Grid Dynamics"
    link: http://www.griddynamics.com
  documentation:
    overview: |
      Thank you for installing Agile Software Factory!
      Checkout the latest documentation here: https://github.com/griddynamics/asf
