application:
  configuration:
    input.cookbooks_url: "http://gd-asf.s3.amazonaws.com/cookbooks.tar.gz"
    input.gerrit_version: "2.8.6"
    input.jira_version: "6.1.5"

  interfaces:
    input:
      cookbooks_url: "bind(jira#input.cookbooks_url, openldap#input.cookbooks_url, jenkins#input.cookbooks_url, gerrit#input.cookbooks_url)"
      jira_version: "bind(jira#input.jira_version)"
      gerrit_version: "bind(gerrit#input.gerrit_version)"
    endpoints:
      jira: "bind(jira#output.jira_endpoint)"
      openldap: "bind(openldap#output.ldap_endpoint)"
      jenkins: "bind(jenkins#output.jenkins_endpoint)"
      gerrit: "bind(gerrit#output.gerrit_endpoint)"
    servers:
      jira_host: "bind(jira#output.public_ips)"
      openldap_host: "bind(openldap#output.public_ips)"
      jenkins_host: "bind(jenkins#output.public_ips)"
      gerrit_host: "bind(gerrit#output.public_ips)"
  components:
      gerrit:
        type: reference.Submodule
        configuration:
            __locator.application-id: "Gerrit"
        interfaces:
          input:
            gerrit_version:
              type: configuration(string)
              name: Gerrit version
            cookbooks_url:
              type: configuration(string)
              name: Cookbooks tarball URL
          output:
            public_ips:
              type: publish-signal(list<string>)
              name: Gerrit
            gerrit_endpoint:
              type: publish-signal(string)
              name: Gerrit

      jenkins:
        type: reference.Submodule
        configuration:
            __locator.application-id: "Jenkins"
        interfaces:
          input:
            cookbooks_url:
              type: configuration(string)
              name: Cookbooks tarball URL
          output:
            public_ips:
              type: publish-signal(list<string>)
              name: Jenkins
            jenkins_endpoint:
              type: publish-signal(string)
              name: Jenkins

      jira:
        type: reference.Submodule
        configuration:
          __locator.application-id: "JIRA"
        interfaces:
          input:
            jira_version:
              type: configuration(string)
              name: JIRA version
            cookbooks_url:
              type: configuration(string)
              name: Cookbooks tarball URL
          output:
            public_ips:
              type: publish-signal(list<string>)
              name: JIRA
            jira_endpoint:
              type: publish-signal(string)
              name: JIRA

      openldap:
        type: reference.Submodule
        configuration:
          __locator.application-id: "OpenLDAP"
        interfaces:
          input:
            cookbooks_url:
              type: configuration(string)
              name: Cookbooks tarball URL
          output:
            public_ips:
              type: publish-signal(list<string>)
              name: OpenLDAP
            ldap_endpoint:
              type: publish-signal(list<string>)
              name: OpenLDAP
