AllCops:
  Exclude:
    - 'metadata.rb'
    - 'Rakefile'
    - 'Guardfile'
    - 'Berksfile'
    - 'Vagrantfile'
    - 'Thorfile'
Style/SpaceInsideHashLiteralBraces:  
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/HashSyntax:
  Enabled: false
