# Encoding: utf-8
#
# Application: Agile Software Factory
# Component: Jenkins
#
# Copyright (c) 2014 Grid Dynamics International, Inc. All Rights Reserved
# Classification level: Public
# Licensed under the Apache License, Version 2.0.
#

application:
  configuration:
    input.cookbooks_url: "http://gd-asf.s3.amazonaws.com/cookbooks.tar.gz"
  interfaces:
    input:
      cookbooks_url: "bind(workflow#input.cookbooks_url)"
    output:
      jenkins_public_ips: "bind(workflow#result.jenkins_public_ips)"
      jenkins_endpoint: "bind(workflow#result.jenkins_endpoint)"
  components:
    workflow:
      type: workflow.Instance
      interfaces:
        input:
          cookbooks_url:
            type: configuration(string)
            name: Cookbooks tarball URL
        result:
          jenkins_public_ips:
            type: publish-signal(list<string>)
            name: "Instance IP:"
          jenkins_endpoint:
            type: publish-signal(string)
            name: "Jenkins WebUI:"
        keypair-store:
          get-keypair: "send-command(string id => object privateKey)"
      configuration:
        configuration.triggers: {}
        configuration.workflows:
          launch:
            steps:
              - start_vm:
                  action: provisionVms
                  parameters:
                    roleName: jenkins
                    hardwareId: m3.medium
                    quantity: 1
                    retryCount: 1
                    jcloudsProvider: aws-ec2
                    jcloudsEndpoint: https://ec2.us-east-1.amazonaws.com
                    jcloudsRegions: us-east-1
                    jcloudsNodeNamePrefix: jenkins
                    vmIdentity: ec2-user
                    imageId: us-east-1/ami-d41689bd
                    ec2SecurityGroup: default
                    providerSettings:
                      userData: "#!/bin/bash\nmkdir -p /etc/chef/ohai/hints\ntouch /etc/chef/ohai/hints/ec2.json"
                  output:
                    jenkins_public_ips: ips
                    private_ips: privateips

              - install_jenkins:
                  action: chefsolo
                  precedingPhases: [ start_vm ]
                  parameters:
                    roles: [ jenkins ]
                    recipeUrl: "{$.cookbooks_url}"
                    runList: [ "recipe[cicd_infrastructure::jenkins]" ]
                    version: "11.8.2"
                  output:
                    chef_attrs: chefState
            return:
              jenkins_public_ips:
                value: "{$.jenkins_public_ips}"
              jenkins_endpoint:
                value: "http://{$.jenkins_public_ips[0]}:8080"
          destroy:
            steps:
              - destroy:
                  action: undeployEnv
