application:
  bindings:
    - [workflow, logger]

  configuration:
    input.jira_version: "5.2.7"
    input.cookbooks_url: "http://gd-asf.s3.amazonaws.com/cookbooks.tar.gz"
  interfaces:
    input:
      jira_version: "bind(workflow#input.jira_version)"
      cookbooks_url: "bind(workflow#input.cookbooks_url)"
    output: 
      public_ips: "bind(workflow#result.public_ips)"
      jira_endpoint: "bind(workflow#result.jira_endpoint)"
      logging-dashboard: "bind(workflow#result.logging-dashboard)"
  components:
    logger:
      type: reference.Service
      interfaces:
        logger:
          logger-server: publish-signal(string)
    workflow:
      type: workflow.Instance
      interfaces:
        input:  
          jira_version: 
            type: configuration(string)
            name: JIRA version
          cookbooks_url:
            type: configuration(string)
            name: Cookbooks tarball URL
        result:  
          public_ips:
            type: publish-signal(list<string>)
            name: "Instance IP: "
          jira_endpoint: 
            type: publish-signal(string)
            name: "JIRA Dashboard: "
          logging-dashboard: 
            type: publish-signal(string)
            name: "Logging Dashboard"
        logger:
          logger-server: consume-signal(string)
        keypair-store:
          get-keypair: "send-command(string id => object privateKey)"

      required: [logger]
      configuration:
        configuration.triggers: {}
        configuration.workflows:
          launch:
            steps:
              - start_vm:
                  action: provisionVmsWithLogging
                  parameters:
                    roleName: jira
                    hardwareId: m1.small
                    quantity: 1
                    retryCount: 1
                    jcloudsProvider: aws-ec2
                    jcloudsEndpoint: https://ec2.us-east-1.amazonaws.com
                    jcloudsRegions: us-east-1
                    jcloudsNodeNamePrefix: jira
                    vmIdentity: ec2-user
                    imageId: us-east-1/ami-d41689bd
                    ec2SecurityGroup: default
                    providerSettings:
                      userData: "#!/bin/bash\nmkdir -p /etc/chef/ohai/hints\ntouch /etc/chef/ohai/hints/ec2.json"
                  output:
                    public_ips: ips
                    private_ips: privateips
                    logging-dashboard: logging-dashboard

              - install_jira:
                  action: chefsolo
                  precedingPhases: [ start_vm ]
                  parameters:
                      roles: [ jira ]
                      recipeUrl: "{$.cookbooks_url}"
                      runList: [ "recipe[cicd_infrastructure::jira]" ]
                      version: "11.12.8"
                      jattrs:
                        jira:
                          version: "{$.jira_version}"
                          install_type: "standalone"
                        java:
                          oracle:
                            accept_oracle_download_terms: true
                  output: 
                    attrs: chefState

              - enable_logging:
                  action: registerLogPath
                  precedingPhases: [ start_vm ]
                  parameters:
                    roles: [ jira ]
                    paths: [ "/opt/atlassian/jira/logs/catalina.out" ]

            return:
              public_ips:
                value: "{$.public_ips}"
              jira_endpoint:
                value: "https://{$.attrs.jira.apache2.virtual_host_name}:{$.chef_attrs.jira.apache2.ssl.port}"
              logging-dashboard:
                value: "{$.logging-dashboard}"
          destroy:
            steps:
                - destroy:
                    action: undeployEnv
