# Encoding: utf-8
#
# Application: Agile Software Factory
# Component: OpenLDAP
#
# Copyright (c) 2014 Grid Dynamics International, Inc. All Rights Reserved
# Classification level: Public
# Licensed under the Apache License, Version 2.0.
#

application:
  configuration:
    input.cookbooks_url: "http://gd-asf.s3.amazonaws.com/cookbooks.tar.gz"
  interfaces:
    input:
      cookbooks_url: "bind(workflow#input.cookbooks_url)"
    output:
      ldap_public_ips: "bind(workflow#result.ldap_public_ips)"
      ldap_endpoint: "bind(workflow#result.ldap_endpoint)"
      ldapadmin_endpoint: "bind(workflow#result.ldapadmin_endpoint)"
  components:
    workflow:
      type: workflow.Instance
      interfaces:
        input:
          cookbooks_url:
            type: configuration(string)
            name: Cookbooks tarball URL
        result:
          ldap_public_ips:
            type: publish-signal(list<string>)
            name: "Instance IP: "
          ldap_endpoint:
            type: publish-signal(list<string>)
            name: "LDAP connnection string: "
          ldapadmin_endpoint:
            type: publish-signal(list<string>)
            name: "LDAP WebUI: "
        keypair-store:
          get-keypair: "send-command(string id => object privateKey)"
      configuration:
        configuration.triggers: {}
        configuration.workflows:
          launch:
            steps:
              - start_vm:
                  action: provisionVms
                  parameters:
                    roleName: ldap
                    hardwareId: t1.micro
                    quantity: 1
                    retryCount: 1
                    jcloudsProvider: aws-ec2
                    jcloudsEndpoint: https://ec2.us-east-1.amazonaws.com
                    jcloudsRegions: us-east-1
                    jcloudsNodeNamePrefix: ldap
                    vmIdentity: ec2-user
                    imageId: us-east-1/ami-c25be3aa
                    securityGroup: default
                    providerSettings:
                      userData: "#!/bin/bash\nmkdir -p /etc/chef/ohai/hints\ntouch /etc/chef/ohai/hints/ec2.json"
                  output:
                    ldap_public_ips: ips
                    private_ips: privateips

              - install_openldap:
                  action: chefsolo
                  precedingPhases: [ start_vm ]
                  parameters:
                    roles: [ ldap ]
                    recipeUrl: "{$.cookbooks_url}"
                    runList: [ "recipe[cicd_infrastructure::openldap]" ]
                    version: "11.8.2"
                  output:
                    chef_attrs: chefState
            return:
              ldap_public_ips:
                value: "{$.ldap_public_ips}"
              ldap_endpoint:
                value: "ldap://{$.ldap_public_ips}:389"
              ldapadmin_endpoint:
                value: "http://{$.ldap_public_ips}/phpldapadmin"
          destroy:
            steps:
              - destroy:
                  action: undeployEnv
