# Encoding: utf-8
#
# Application: Agile Software Factory
# Component: Sonar
#
# Copyright (c) 2014 Grid Dynamics International, Inc. All Rights Reserved
# Classification level: Public
# Licensed under the Apache License, Version 2.0.
#

application:
  configuration:
    input.sonar_version: "3.7.4"
    input.cookbooks_url: "http://gd-asf.s3.amazonaws.com/cookbooks.tar.gz"
  interfaces:
    input:
      sonar_version: "bind(workflow#input.sonar_version)"
      cookbooks_url: "bind(workflow#input.cookbooks_url)"
    output:
      sonar_public_ips: "bind(workflow#result.sonar_public_ips)"
      sonar_endpoint: "bind(workflow#result.sonar_endpoint)"
  components:
    workflow:
      type: workflow.Instance
      interfaces:
        input:
          sonar_version:
            type: configuration(string)
            name: Sonar version
          cookbooks_url:
            type: configuration(string)
            name: Cookbooks tarball URL
        result:
          sonar_public_ips:
            type: publish-signal(list<string>)
            name: "Instance IP"
          sonar_endpoint:
            type: publish-signal(list<string>)
            name: "Sonar URL"
        keypair-store:
          get-keypair: "send-command(string id => object privateKey)"
      configuration:
        configuration.triggers: {}
        configuration.workflows:
          launch:
            steps:
              - start_vm:
                  action: provisionVms
                  parameters:
                    roleName: sonar
                    hardwareId: m1.small
                    quantity: 1
                    retryCount: 1
                    jcloudsProvider: aws-ec2
                    jcloudsEndpoint: https://ec2.us-east-1.amazonaws.com
                    jcloudsRegions: us-east-1
                    jcloudsNodeNamePrefix: sonar
                    vmIdentity: ec2-user
                    imageId: us-east-1/ami-d41689bd
                    ec2SecurityGroup: default
                    providerSettings:
                      userData: "#!/bin/bash\nmkdir -p /etc/chef/ohai/hints\ntouch /etc/chef/ohai/hints/ec2.json"
                  output:
                    sonar_public_ips: ips
                    private_ips: privateips

              - install_sonar:
                  action: chefsolo
                  precedingPhases: [ start_vm ]
                  parameters:
                    roles: [ sonar ]
                    recipeUrl: "{$.cookbooks_url}"
                    runList: [ "recipe[cicd_infrastructure::sonar]" ]
                    version: "11.8.2"
                    jattrs:
                      sonar:
                        version: "{$.sonar_version}"
                  output:
                    chef_attrs: chefState
            return:
              sonar_public_ips:
                value: "{$.sonar_public_ips}"
              sonar_endpoint:
                value: "http://{$.sonar_public_ips}:9000"
          destroy:
            steps:
              - destroy:
                  action: undeployEnv
